# Generated by Django 5.1.1 on 2024-09-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
