# Generated by Django 5.1.1 on 2024-09-11 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_user_created_at_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification',
        ),
        migrations.AddField(
            model_name='customuser',
            name='new_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
