# Generated by Django 5.1.1 on 2024-09-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
