# Generated by Django 5.1.1 on 2024-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(default='CBS 403 - Ethical Hacking and Penetration Testing', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.CharField(max_length=50),
        ),
    ]
