# Generated by Django 5.1.1 on 2024-09-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_userprofile_course_alter_userprofile_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
