# Generated by Django 5.1.1 on 2024-09-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
