# Generated by Django 5.1.1 on 2024-09-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_rename_image_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='images/default_profile.jpg', upload_to='profile_images/'),
        ),
    ]
