# Generated by Django 5.1.1 on 2024-09-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
