# Generated by Django 5.1.1 on 2024-09-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
