# Generated by Django 5.1.1 on 2024-09-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
