# Generated by Django 5.1.1 on 2024-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
