# Generated by Django 5.1.1 on 2024-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_blogpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted_data_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
