# Generated by Django 5.1.1 on 2024-10-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_userprofile_accepted_data_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('tooltip', models.TextField()),
                ('vulnerability', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_node', to='myapp.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_node', to='myapp.node')),
            ],
        ),
    ]
