# Generated by Django 5.1.1 on 2024-10-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_remove_wire_start_node_remove_wire_end_node_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('tooltip', models.TextField()),
                ('vulnerability', models.TextField(blank=True, null=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('icon', models.CharField(max_length=255)),
                ('demo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_id', models.IntegerField()),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_wires', to='myapp.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_wires', to='myapp.node')),
            ],
        ),
    ]
