# Generated by Django 5.1.1 on 2024-10-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_node_wire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wire',
            name='start_node',
        ),
        migrations.RemoveField(
            model_name='wire',
            name='end_node',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Wire',
        ),
    ]
