# Generated by Django 5.1.1 on 2024-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_node_wire'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.JSONField()),
                ('wires', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='wire',
            name='target_node',
        ),
        migrations.RemoveField(
            model_name='wire',
            name='source_node',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Wire',
        ),
    ]
