# Generated by Django 5.1.1 on 2024-10-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_canvas_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasState',
        ),
    ]
