# Generated by Django 5.1.1 on 2024-10-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_delete_canvasstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.JSONField()),
                ('wires', models.JSONField()),
            ],
        ),
    ]
