# Generated by Django 5.1.1 on 2024-10-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_canvasstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='canvas',
        ),
        migrations.DeleteModel(
            name='CanvasState',
        ),
        migrations.DeleteModel(
            name='Canvas',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
