# Generated by Django 5.1.1 on 2024-10-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_canvasstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasState',
        ),
    ]
