# Generated by Django 5.1.1 on 2024-10-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_delete_canvasstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=15)),
                ('tooltip_description', models.TextField(blank=True, null=True)),
                ('vulnerability', models.CharField(blank=True, max_length=255, null=True)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_wire', to='myapp.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_wire', to='myapp.node')),
            ],
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.ManyToManyField(to='myapp.node')),
                ('wires', models.ManyToManyField(to='myapp.wire')),
            ],
        ),
    ]
