# Generated by Django 5.1.1 on 2024-10-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_remove_wire_end_node_remove_wire_start_node_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.JSONField()),
                ('wires', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
