# Generated by Django 5.1.1 on 2024-10-15 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_remove_wire_end_node_remove_wire_start_node_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=45)),
                ('vulnerability', models.CharField(max_length=255)),
                ('tooltip', models.TextField(blank=True, null=True)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='myapp.canvas')),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wires', to='myapp.canvas')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_wires', to='myapp.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_wires', to='myapp.node')),
            ],
        ),
    ]
