# Generated by Django 5.1.1 on 2024-10-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0084_canvas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canvas',
        ),
    ]
