# Generated by Django 5.1.1 on 2024-10-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0088_node_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
