# Generated by Django 5.1.1 on 2024-11-16 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0094_nodeassessment_delete_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeassessment',
            old_name='points',
            new_name='overall_points',
        ),
        migrations.RemoveField(
            model_name='nodeassessment',
            name='node_id',
        ),
        migrations.AddField(
            model_name='nodeassessment',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
