# Generated by Django 5.1.1 on 2024-11-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0095_rename_points_nodeassessment_overall_points_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeAssessment',
        ),
    ]
