# Generated by Django 5.1.1 on 2024-11-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0099_nodeassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeAssessment',
        ),
    ]
