# Generated by Django 5.1.1 on 2024-11-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0101_nodeassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeAssessment',
        ),
    ]
