# Generated by Django 5.1.1 on 2024-11-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0103_nodeassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeassessment',
            name='canvas_state_id',
        ),
        migrations.RemoveField(
            model_name='nodeassessment',
            name='score',
        ),
    ]
