# Generated by Django 5.1.1 on 2024-11-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0104_remove_nodeassessment_canvas_state_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeAssessment',
        ),
    ]
