# Generated by Django 5.1.1 on 2024-11-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0106_canvassubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasSubmission',
        ),
    ]
