# Generated by Django 5.1.1 on 2024-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0108_assessmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_id', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('submission_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='AssessmentSubmission',
        ),
    ]
