# Generated by Django 5.1.1 on 2024-11-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0110_assessment_delete_canvasassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
