# Generated by Django 5.1.1 on 2024-11-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0114_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='canvas_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
