# Generated by Django 5.1.1 on 2024-11-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0115_score_canvas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='canvas_id',
        ),
        migrations.AddField(
            model_name='score',
            name='canvas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.canvasstate'),
        ),
    ]
