# Generated by Django 5.1.1 on 2024-11-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0116_remove_score_canvas_id_score_canvas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='canvas',
        ),
        migrations.AddField(
            model_name='score',
            name='canvas_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
