# Generated by Django 5.1.1 on 2024-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0117_remove_score_canvas_score_canvas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='canvas_id',
        ),
        migrations.AddField(
            model_name='score',
            name='canvas_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
