# Generated by Django 5.1.1 on 2024-11-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0118_remove_score_canvas_id_score_canvas_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='canvas_title',
        ),
    ]
