# Generated by Django 5.1.1 on 2024-11-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0119_remove_score_canvas_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
