# Generated by Django 5.1.1 on 2024-11-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0120_score_finished'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasState',
        ),
    ]
