# Generated by Django 5.1.1 on 2024-11-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0123_canvasstatedefend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
