# Generated by Django 5.1.1 on 2024-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0126_score_incorrect_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='incorrect_count',
            new_name='correct_submissions',
        ),
        migrations.AddField(
            model_name='score',
            name='incorrect_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
