# Generated by Django 5.1.1 on 2024-11-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0128_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasState',
        ),
    ]
