# Generated by Django 5.1.1 on 2024-11-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0130_canvasstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('chart_type', models.CharField(max_length=100)),
            ],
        ),
    ]
