# Generated by Django 5.1.1 on 2024-11-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0131_graphanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphAnalysis',
        ),
    ]
