# Generated by Django 5.1.1 on 2024-11-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0133_analysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
