# Generated by Django 5.1.1 on 2024-11-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0135_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='content',
        ),
        migrations.AddField(
            model_name='analysis',
            name='areachart_graph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='bar_graph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='pie_graph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
