# Generated by Django 5.1.1 on 2024-11-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0136_remove_analysis_content_analysis_areachart_graph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseCode', models.CharField(max_length=100)),
                ('CourseName', models.CharField(max_length=200)),
                ('CourseDesc', models.TextField()),
                ('Program', models.CharField(max_length=200)),
                ('Section', models.CharField(max_length=50)),
            ],
        ),
    ]
