# Generated by Django 5.1.1 on 2024-11-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0137_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
