# Generated by Django 5.1.1 on 2024-11-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0139_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasStateDefend',
        ),
    ]
