# Generated by Django 5.1.1 on 2024-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0141_canvasstatedefend'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='challenge_definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
