# Generated by Django 5.1.1 on 2024-11-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0142_analysis_challenge_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='canvas_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.canvasstate'),
        ),
    ]
