# Generated by Django 5.1.1 on 2024-11-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0143_score_canvas_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='canvas_state',
        ),
        migrations.AddField(
            model_name='score',
            name='canvas_state_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
