# Generated by Django 5.1.1 on 2024-11-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0145_alter_userprofile_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
