# Generated by Django 5.1.1 on 2024-11-20 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0146_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default_QBRSs97.jpg', null=True, upload_to='profile_images/')),
                ('is_online', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('accepted_data_privacy', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
