# Generated by Django 5.1.1 on 2024-11-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0148_alter_userprofile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
