# Generated by Django 5.1.1 on 2024-11-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0150_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasState',
        ),
    ]
