# Generated by Django 5.1.1 on 2024-11-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0152_canvasstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasStateDefend',
        ),
    ]
