# Generated by Django 5.1.1 on 2024-11-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0154_canvasstatedefend'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='split_graph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
