# Generated by Django 5.1.1 on 2024-11-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0155_analysis_split_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_graph', models.TextField(blank=True, null=True)),
                ('pie_graph', models.TextField(blank=True, null=True)),
                ('areachart_graph', models.TextField(blank=True, null=True)),
                ('split_graph', models.TextField(blank=True, null=True)),
                ('data_checksum', models.CharField(max_length=32)),
                ('challenge_definition', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
