# Generated by Django 5.1.1 on 2024-11-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0156_studentanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnalysis',
        ),
    ]
