# Generated by Django 5.1.1 on 2024-11-22 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0157_delete_studentanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_graph', models.TextField(blank=True, null=True)),
                ('pie_graph', models.TextField(blank=True, null=True)),
                ('areachart_graph', models.TextField(blank=True, null=True)),
                ('split_graph', models.TextField(blank=True, null=True)),
                ('data_checksum', models.CharField(max_length=32)),
                ('challenge_definition', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
