# Generated by Django 5.1.1 on 2024-11-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0159_alter_userprofile_course_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasState',
        ),
    ]
