# Generated by Django 5.1.1 on 2024-11-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0161_canvasstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasStateDefend',
        ),
    ]
