# Generated by Django 5.1.1 on 2024-11-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0163_canvasstatedefend'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='closed_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
