# Generated by Django 5.1.1 on 2024-11-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0164_score_closed_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasstate',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='canvasstate',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
