# Generated by Django 5.1.1 on 2024-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0165_canvasstate_access_count_canvasstate_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasstatedefend',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='canvasstatedefend',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
