# Generated by Django 5.1.1 on 2024-11-27 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0166_canvasstatedefend_access_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='Program',
            field=models.CharField(max_length=100),
        ),
    ]
