# Generated by Django 5.1.1 on 2024-11-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0167_course_published_by_alter_course_coursecode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasstate',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='canvasstate',
            name='locked',
        ),
        migrations.AddField(
            model_name='score',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
