# Generated by Django 5.1.1 on 2024-11-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0168_remove_canvasstate_access_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='score',
            name='locked',
        ),
    ]
