# Generated by Django 5.1.1 on 2024-11-27 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0170_canvasinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasinteraction',
            name='canvas_state_defend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.canvasstatedefend'),
        ),
        migrations.AlterField(
            model_name='canvasinteraction',
            name='canvas_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.canvasstate'),
        ),
    ]
