# Generated by Django 5.1.1 on 2024-11-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0171_canvasinteraction_canvas_state_defend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasstatedefend',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='canvasstatedefend',
            name='locked',
        ),
    ]
