# Generated by Django 5.1.1 on 2024-12-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0172_remove_canvasstatedefend_access_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasstate',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
