# Generated by Django 5.1.1 on 2024-12-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0173_canvasstate_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasstate',
            name='canvas_scenario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
