# Generated by Django 5.1.1 on 2024-12-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0174_canvasstate_canvas_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='canvas_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
