# Generated by Django 5.1.1 on 2024-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0175_score_canvas_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total_possible_correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='total_possible_score',
            field=models.IntegerField(default=0),
        ),
    ]
